"""pgfplots figures for the violations study (new files only; same conventions as make_pgfplots.py).

  figures/violations_by_k.tex       violation rate vs k per problem for M1, M2, M3 (literal, favorable),
  figures/violations_by_k_wide.tex  A1, A2 -- rows with OPT on the n = 20 instances (k = 1..20, all seeds)
  figures/violations_lambda.tex     diverse rec n = 20: violation rate, mean severity (violated rows)
                                    and fraction of monotone seeds vs lambda
Data: data/violations_by_k__<problem>.dat, data/violations_lambda.dat.
Reads <problem>/results/*_violations.csv and diverse_recommendation/results/lambda_sweep_violations.csv.
M3-literal rates are over the rows where its LP is feasible (infeasible = no bound produced).

Usage: python3 latex/make_violation_plots.py        (needs pandas)
"""
import glob
import math
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROBLEMS = [("src", "max_cut", "Max-cut"), ("directed_cut", "directed_cut", "Directed cut"),
            ("revenue_max", "revenue_max", "Revenue max."), ("diverse_recommendation", "diverse_rec", "Diverse rec."),
            ("log_determinant", "log_det", "Log-determinant"), ("gaussian_mi", "gaussian_mi", "Gaussian MI"),
            ("hypergraph_cut", "hypergraph_cut", "Hypergraph cut")]
METHODS = [("m1", "vm1", "M1 (BQS Dual)"), ("m2", "vm2", "M2 (Marginal, no penalty)"),
           ("m3lit", "vm3lit", "M3 literal"), ("m3fav", "vm3fav", "M3 favorable"),
           ("a1", "va1", "A1 (caps, no penalty)"), ("a2", "va2", "A2 (penalty, raw caps)")]


def fmt(v):
    return "nan" if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.5f}"


def write_dat(path, df, xcol, cols, comment):
    with open(path, "w") as f:
        f.write(f"# {comment}\n{xcol} " + " ".join(cols) + "\n")
        for _, r in df.iterrows():
            f.write(f"{r[xcol]:g} " + " ".join(fmt(r[c]) for c in cols) + "\n")


def legend(columns):
    out = ["\\begin{tikzpicture}", f"\\begin{{axis}}[rglegendaxis, legend columns={columns}]"]
    for _, style, label in METHODS:
        out.append(f"\\addlegendimage{{{style}}}\\addlegendentry{{{label}}}")
    out += ["\\end{axis}", "\\end{tikzpicture}"]
    return "\n".join(out)


def by_k():
    panels = []
    for folder, key, title in PROBLEMS:
        files = [f for f in glob.glob(os.path.join(ROOT, folder, "results", "*_violations.csv"))
                 if not os.path.basename(f).startswith("lambda_sweep")]  # own figure
        if not files:
            continue
        df = pd.concat([pd.read_csv(f) for f in files])
        df = df[(df["n"] == 20) & (df["ref_kind"] == "opt")]
        if df.empty:
            continue
        g = df.groupby("k")[[f"{m}_violated" for m, _, _ in METHODS]].mean().reset_index()
        g.columns = ["k"] + [m for m, _, _ in METHODS]
        write_dat(os.path.join(HERE, "data", f"violations_by_k__{key}.dat"), g, "k", [m for m, _, _ in METHODS],
                  f"{title}: violation rate vs k over n = 20 rows with OPT ({df['label'].nunique()} instance(s), "
                  f"{len(df)} rows); nan = no bound produced")
        panels.append((key, title, int(df["label"].nunique()), int(df["seed"].nunique())))
    return panels


def panel_tex(key, title):
    lines = ["\\begin{tikzpicture}", "\\begin{axis}[rgaxisbase, ymin=0, ymax=1.05, xmin=1, xmax=20,",
             f"    title={{{title} ($n=20$)}}, ylabel={{Violation rate}},", "]"]
    for i, (m, style, _) in enumerate(METHODS):
        lines.append(f"\\addplot[{style}, mark repeat=3, mark phase={1 + i % 3}] table[x=k, y={m}] "
                     f"{{\\rgroot/data/violations_by_k__{key}.dat}};")
    lines += ["\\end{axis}", "\\end{tikzpicture}"]
    return "\n".join(lines)


def figure(panels, wide):
    env = "figure*" if wide else "figure"
    per_row = 4 if wide else 2
    out = [f"% violation rate vs k (generated by make_violation_plots.py)", f"\\begin{{{env}}}[t]", "\\centering",
           "\\setlength{\\rgplotwidth}{" + ("0.245\\textwidth" if wide else "0.49\\columnwidth") + "}",
           legend(3 if wide else 2) + "\\\\[1pt]"]
    for i, (key, title, _, _) in enumerate(panels):
        sep = "\\\\" if (i + 1) % per_row == 0 and i + 1 < len(panels) else ("\\hfill" if i + 1 < len(panels) else "")
        out.append(panel_tex(key, title) + sep)
    out.append("\\caption{Fraction of rows ($n = 20$ instances, all seeds, OPT by brute force) on which a "
               "published monotone upper bound, or an ablation of the dual bound, falls below OPT$_k$, as a "
               "function of $k$. M1: BQS Dual; M2: Marginal without penalty; M3: Zhang--Tang--Tang "
               "$\\Lambda^{3*}$ with nonnegative (literal) or free (favorable) increments, rates over the rows "
               "where its LP is feasible; A1: the dual bound without its penalty; A2: the dual bound with the "
               "raw prefix caps $f_S(A_i)$. The controls (top-$k$, Marginal, dual bound, B2, B5) never "
               "violate.}")
    out.append(f"\\label{{fig:violations-by-k{'-wide' if wide else ''}}}")
    out.append(f"\\end{{{env}}}")
    return "\n".join(out) + "\n"


def lam():
    path = os.path.join(ROOT, "diverse_recommendation", "results", "lambda_sweep_violations.csv")
    if not os.path.exists(path):
        return False
    df = pd.read_csv(path)
    rows = []
    for L, g in df.groupby("lambda"):
        r = {"lambda": L, "mono": g.groupby("seed")["monotone_flag"].first().mean()}
        for m, _, _ in METHODS:
            r[m] = g[f"{m}_violated"].mean()
            v = g[g[f"{m}_violated"] == 1]
            r[f"{m}_sev"] = v[f"{m}_severity"].mean() if len(v) else math.nan  # undefined without violations
        rows.append(r)
    t = pd.DataFrame(rows)
    cols = ["mono"] + [m for m, _, _ in METHODS] + [f"{m}_sev" for m, _, _ in METHODS]
    write_dat(os.path.join(HERE, "data", "violations_lambda.dat"), t, "lambda", cols,
              "diverse rec n = 20, 10 seeds, k = 1..20: violation rate, mean severity (violated rows), monotone seeds")
    def ax(ycol_suffix, ylabel, title, extra=""):
        lines = ["\\begin{tikzpicture}",
                 "\\begin{axis}[rgaxisbase, xmin=0, xmax=1.5, xlabel={$\\lambda$},",
                 f"    title={{{title}}}, ylabel={{{ylabel}}}, xtick={{0,0.5,1,1.5}},",
                 f"    minor xtick={{0.1,0.25,0.75}},{extra}", "]"]
        for m, style, _ in METHODS:
            lines.append(f"\\addplot[{style}] table[x=lambda, y={m}{ycol_suffix}] {{\\rgroot/data/violations_lambda.dat}};")
        if not ycol_suffix:
            lines.append("\\addplot[black, densely dashed, line width=0.9pt] table[x=lambda, y=mono] "
                         "{\\rgroot/data/violations_lambda.dat};")
        lines += ["\\end{axis}", "\\end{tikzpicture}"]
        return "\n".join(lines)
    fig = ["% violations vs lambda (generated by make_violation_plots.py)", "\\begin{figure}[t]", "\\centering",
           "\\setlength{\\rgplotwidth}{0.49\\columnwidth}", legend(2),
           "\\begin{tikzpicture}\\begin{axis}[rglegendaxis]\\addlegendimage{black, densely dashed, line width=0.9pt}"
           "\\addlegendentry{monotone seeds (fraction)}\\end{axis}\\end{tikzpicture}\\\\[1pt]",
           ax("", "Violation rate", "Violation rate", " ymax=1.05,") + "\\hfill",
           ax("_sev", "(OPT $-$ bound) / OPT", "Mean severity (log)",
              " ymode=log, ymin=1e-3, ymax=10, ytick={0.001,0.01,0.1,1,10},"),
           "\\caption{Diverse recommendation with $n = 20$ (10 seeds, $k = 1,\\dots,20$, OPT by brute force) as "
           "$\\lambda$ varies: $f$ is monotone for $\\lambda \\le 1/2$. Left: fraction of rows on which each method "
           "falls below OPT$_k$ (dashed: fraction of monotone seeds). Right: mean relative shortfall over the "
           "violated rows (log scale; not shown where a method has no violation). M3-literal is over the rows where "
           "its LP is feasible.}",
           "\\label{fig:violations-lambda}", "\\end{figure}"]
    with open(os.path.join(HERE, "figures", "violations_lambda.tex"), "w") as f:
        f.write("\n".join(fig) + "\n")
    return True


def main():
    for d in ("data", "figures"):
        os.makedirs(os.path.join(HERE, d), exist_ok=True)
    panels = by_k()
    for wide in (False, True):
        with open(os.path.join(HERE, "figures", f"violations_by_k{'_wide' if wide else ''}.tex"), "w") as f:
            f.write(figure(panels, wide))
    print(f"violations_by_k: {len(panels)} panels; violations_lambda: {'written' if lam() else 'no data yet'}")


if __name__ == "__main__":
    main()
